"""Central configuration for the LoSLOPE backend."""
import os
from pathlib import Path

try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parent.parent / ".env")
except Exception:
    pass  # dotenv optional; env vars still work without it


def _env(key: str, default: str = "") -> str:
    return os.environ.get(key, default).strip()


# --- Paths -----------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
DB_PATH = BASE_DIR / "loslope.db"
MODEL_DIR = BASE_DIR / "models"
MODEL_DIR.mkdir(exist_ok=True)

# Built frontend (served by FastAPI when present, e.g. behind a tunnel).
FRONTEND_DIST = BASE_DIR.parent / "frontend" / "dist"

# --- HiveMQ / MQTT ---------------------------------------------------------
# The backend subscribes to this broker and ingests every reading the base
# station publishes. Set these via environment variables (see .env.example)
# so credentials are never committed.
#   MQTT_HOST  e.g. abcd1234.s1.eu.hivemq.cloud
#   MQTT_PORT  8883 for TLS (HiveMQ Cloud default)
#   MQTT_USER / MQTT_PASS  the broker credentials you created in HiveMQ
#   MQTT_TOPIC topic the base station publishes to
def _clean_host(raw: str) -> str:
    """Tolerate a host pasted with a scheme, :port, or trailing path so a
    value like 'mqtts://host:8883/' still resolves to just 'host'."""
    h = raw.strip()
    if "://" in h:
        h = h.split("://", 1)[1]
    h = h.split("/", 1)[0]    # drop any path
    h = h.split(":", 1)[0]    # drop any :port
    return h


MQTT_HOST = _clean_host(_env("MQTT_HOST"))
MQTT_PORT = int(_env("MQTT_PORT", "8883"))
MQTT_USER = _env("MQTT_USER")
MQTT_PASS = _env("MQTT_PASS")
MQTT_TOPIC = _env("MQTT_TOPIC", "loslope/readings")
MQTT_TLS = _env("MQTT_TLS", "true").lower() != "false"
# MQTT is only started when a host is configured.
MQTT_ENABLED = bool(MQTT_HOST)

# --- Deployment ------------------------------------------------------------
# On a fresh cloud container the SQLite DB starts empty; seed demo nodes +
# readings so the dashboard is populated and the ML can train on day one.
AUTO_SEED = _env("AUTO_SEED", "true").lower() != "false"

# --- Alerting (Telegram + optional Gemini) ---------------------------------
# When a WARNING/CRITICAL reading is ingested the backend composes an alert
# and sends it to Telegram. Message text is generated by Gemini when a key is
# set, otherwise by a built-in template (the template is also the fallback if
# Gemini errors or is rate-limited).
TELEGRAM_BOT_TOKEN = _env("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = _env("TELEGRAM_CHAT_ID")
TELEGRAM_ENABLED = bool(TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID)

# Google Gemini (free tier). Leave GEMINI_API_KEY blank to use the template.
GEMINI_API_KEY = _env("GEMINI_API_KEY")
GEMINI_MODEL = _env("GEMINI_MODEL", "gemini-2.0-flash")
GEMINI_ENABLED = bool(GEMINI_API_KEY)

# Minimum level that triggers an alert (2 = WARNING). Repeat CRITICAL alerts
# are suppressed unless this many seconds have passed since the last one.
ALERT_MIN_LEVEL = int(_env("ALERT_MIN_LEVEL", "2"))
ALERT_COOLDOWN_SECONDS = int(_env("ALERT_COOLDOWN_SECONDS", "120"))

# --- Behaviour -------------------------------------------------------------
# A node is considered offline if no reading has arrived within this window.
OFFLINE_SECONDS = 60

# Retrain the ML models automatically after this many newly ingested readings.
RETRAIN_EVERY_N = 25

# Alert level names, indexed by the integer `lvl` field.
LEVEL_NAMES = ["NORMAL", "WATCH", "WARNING", "CRITICAL"]

# Engineering thresholds used by the synthetic data generator and the
# ML-based time-to-critical forecast. These mirror the firmware thresholds.
CRITICAL_TILT_DEV = 6.0      # degrees
CRITICAL_SOIL = 80.0         # % saturation
